apiVersion: v1
kind: Service

metadata:
  name: buildspace-sample-service

spec:
  selector:
    app: buildspace-sample

  type: NodePort

  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007